name: CI/CD Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build0test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build da imagem
        run: docker build -t backend:latest .

      - name: Definir repo e tag
        id: vars
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "repo=${{ secrets.DOCKER_USERNAME }}/backend" >> $GITHUB_OUTPUT
            echo "tag=latest" >> $GITHUB_OUTPUT

          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "repo=${{ secrets.DOCKER_USERNAME }}/backend" >> $GITHUB_OUTPUT
            echo "tag=dev" >> $GITHUB_OUTPUT

          else
            echo "repo=${{ secrets.DOCKER_USERNAME }}/backend" >> $GITHUB_OUTPUT
            echo "tag=pr" >> $GITHUB_OUTPUT
          fi
      - name: Build imagem final
        run: docker build -t ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }} .

      - name: Push imagem
        run: docker push ${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.tag }}
